---
version: "3" # Always define the version of the compose file specification you use, to avoid ambiguity
services:
  docker-web-app: # Name of our service, we can chose whatever we want

    # Build configuration
    build:
      context: .

    # All below is runtime configuration, equivalent to docker run command line
    container_name: docker-web-app
    # Here we use latest because we most likely want to test our freshly built image
    # But we should always be very careful when using latest
    # To avoid images being replaced "under our noses"
    image: docker-web-app:latest
    ports:
     - 8080:80
    volumes: # Here we use bind mounts as volumes
     - ${LOG_DIR}:/var/logs # ${VAR} will be replace by the environment variable VAR
     - ${HTML_DIR}:/var/www/html # We bind the HTML assets folder to /var/www/html
    environment:
      - MAX_HEADER_SIZE=4096
      - HTML_FOLDER=/var/www/html # We tell the app that the assets are in /var/www/html
    # We can override the CMD instruction of the Docker file (like we do in the docker run command line)
    command: ["npm", "start", "--log-file", "/var/logs/docker_http.log"]
    restart: unless-stopped
