---
version: "3"
services:
  docker-web-app:
    build:
      context: .
    container_name: docker-web-app
    # Here we use latest because we most likely want to test our freshly built image
    # But we should always be very careful when using latest
    # To avoid images being replaced "under our noses"
    image: docker-web-app:latest
    ports:
     - 8080:80
    environment:
     - MAX_HEADER_SIZE=4096
     - LOG_DIR=/var/logs
     - HTML_FOLDER=/var/www
    volumes:
     - ${LOG_DIR}:/var/logs
     - ${HTML_DIR}:/var/www
    command: ["--log-file", "/var/logs/docker_http.log"]
    restart: unless-stopped
